##########################################################
# Project:       ANC350V3 Control Library
#
# Filename:      makefile
#
# Purpose:       Makefile for example 0 for GCC
##########################################################
# $Id: makefile.lx,v 1.4 2015/12/15 17:14:47 trurl Exp $

example0: example0.c
	gcc -o example0 -g -Wall example0.c -I../inc -L../lib -lanc350v4 -lpthread

